apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: spring
        env:
          - name: HOST
            value: "192.168.1.9"
        imagePullPolicy: IfNotPresent
        image: spring-boot:1.0
        ports:
        - containerPort: 8080
