apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-spring
  template:
    metadata:
      labels:
        app: front-spring
    spec:
      containers:
      - name: nginx
        image: us.gcr.io/proyecto-kubernetes-297222/front-spring
        ports:
        - containerPort: 8080